series: GLM Math
title: Transforms Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: In this demo we explore how to apply transformations to vertices.
language: C++
tags:
  - Math
extra_resources:
connections:
  - series: GLFW Graphics
    title: Improved 3D
